### PR TITLE
Added app icon and splash screen

### PR DESCRIPTION
**Pull request by heyman333**
## Description

- added app icon and animated splash screen

## Related Issues

#8 

## Tests

I added the following tests:
simple snapshot test in `AuthLoadingScreen`

## Checklist

- [X] I read the [Contributor Guide](https://github.com/dooboolab/whatssub/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
- [X] I signed the [CLA].
- [X] Run `yarn test` or `yarn test -u` if you need to update snapshot.
- [X] Run `yarn lint`
- [X] I am willing to follow-up on review comments in a timely manner.

## Screenshot
ezgif com-video-to-gif

### CODE REVIEW

**Comment by heyman333** [comment]
@hyochan hello. It is a small part, but I'm happy to contribute to this project
As you can see from the screenshot, the splash image you gave captured the iOS screenshot as it is (iPhone X size). 

I think you have to give the splash image with only the center animation and available sizes on all devices.

thanks.

**Comment by hyochan** [comment]
@heyman333 This looks fabulous!! 🎉 Great job 💯 

image

Could you make an update with the above image then?

**Comment by heyman333** [comment]
@hyochan 
I mean, the image you gave me seems to be only available on iPhone X, so I need a generic-sized gif image that can be used on other devices.
(no notch design applied bottom, no time info over the screen...)

I'll attatch a splash image you gave me, and please see what's wrong 😂


01-splash

**Comment by hyochan** [comment]
@@heyman333 Got one for you~! Please check above image.

**Comment by heyman333** [comment]
@hyochan okay👍

**Comment by heyman333** [comment]
@hyochan 
I think all the work is done now. 👏
However, I did not know the text style of a `copywrite word(ⓒ Whatssub Studio)` on a splash screen, and applied it as a default font. 

If you think that I should work together in this `PR`, please let me know specific style information (font style, etc...)

**Comment by heyman333** [comment]
@hyochan Just updated!

**Comment by hyochan** [comment]
@all-contributors please add @heyman333  for code.

**Comment by hyochan** [comment]
@heyman33 Please submit your `PR` address in [issuehunt](https://issuehunt.io/r/dooboolab/whatssub/issues/8) to grant the reward!
image

**Comment by heyman333** [comment]
@hyochan  I submitted my `pr` Can I just wait now?

**Comment by hyochan** [comment]
@heyman333 You've got it 🎉

**Pull request merged**
